# Generated by Django 3.2 on 2021-04-07 20:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 7, 20, 45, 44, 352730, tzinfo=utc), verbose_name='Date'),
            preserve_default=False,
        ),
    ]
